version: '3.8'
services:
  mysql:
    container_name: mysql
    image: library/mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=mimuse_db
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 6033:80
    environment:
      - PMA_ARBITRARY=1
  redis:
    image: redis
    container_name: redis
    depends_on:
      - mysql
    expose:
      - 6379
  app:
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
      - "redis"
    #entrypoint: ./wait-for-it.sh mysql:3306 -t 0 -- go run .
    build:
      context: .
      dockerfile: ./docker/Dockerfile